version: '3.8'

services:
  
  reranker:
    build:
      context: ./src/reranker
      dockerfile: Dockerfile
    image: mabentley/reranker:latest
    container_name: reranker
    ports:
      - "8000:8000"  # REST API

  embedding:
    build:
      context: ./src/embedding
      dockerfile: Dockerfile
    image: mabentley/embedding:latest
    container_name: embedding
    ports:
      - "8001:8000"  # REST API

  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant
    ports:
      - "6333:6333"  # REST API
      - "6334:6334"  # gRPC API
    # volumes:
    #   - qdrant_storage:/qdrant/storage
    environment:
      - QDRANT__SERVICE__GRPC_PORT=6334

# volumes:
#   qdrant_storage:
